#!/usr/bin/env bash
# script that display "Best School" 10 time
# 9th iteration displays "Best School" then "hi"
i=0
while [ $i -lt 10 ]
do
 if [ $i -eq 9 ]
 then
  echo "Hi"
 fi
 echo "Best School"
 ((i++))
done
