#!/usr/bin/env bash
# a script that display 1 to 20
# 4 and then back luck from china for 4th iteration
# 9 and then bad luch from japan for 9th iteration
# 17 and then bad luck from italy for 17th iteration
i=1
while [ $i -le 20 ]
 do
 echo "$i"
 case $i in
  "4") echo "bad luck from china";;
  "9") echo "bad luck from japan";;
  "17") echo "bad luck from italy"
 esac
 ((i++))
done
